# TEST LOCAL
redis:
    image: redis
    ports:
        - "6380:6379"
mysql:
    image: mysql
    ports:
        - "3307:3306"
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=seekstock
    volumes:
        - /Users/rjarmstrong/data/mysql/test:/var/lib/mysql


