/**
 * Created by Anthony on 2017/3/27.
 */
var raw={ products:
    [ { id: '0adfd74a-15df-11e7-f182-0a921c5bbcc5',
        source_id: '',
        variant_source_id: '',
        handle: 'Sunglasses',
        type: 'Fashion',
        has_variants: false,
        variant_parent_id: '',
        variant_option_one_name: '',
        variant_option_one_value: '',
        variant_option_two_name: '',
        variant_option_two_value: '',
        variant_option_three_name: '',
        variant_option_three_value: '',
        active: true,
        name: 'Sunglasses',
        base_name: 'Sunglasses',
        description: 'Retro square sunglasses with tinted or polarizing lenses.',
        image: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-thumb.png',
        image_large: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-original.png',
        images: [],
        sku: '10012',
        tags: 'Retro square, Summer',
        brand_id: '0adfd74a-15df-11e7-f182-0a921c659e96',
        brand_name: 'In The Shade',
        supplier_name: 'Ramons',
        supplier_code: '',
        supply_price: '50.00',
        account_code_purchase: '',
        account_code_sales: '',
        track_inventory: true,
        button_order: '',
        inventory: [Object],
        price_book_entries: [Object],
        price: 173.91304,
        tax: 26.08696,
        tax_id: '0adfd74a-1555-11e7-f182-0a921c213ccb',
        tax_rate: 0.15,
        tax_name: 'GST',
        taxes: [Object],
        display_retail_price_tax_inclusive: 1,
        updated_at: '2017-03-16 21:47:12',
        deleted_at: '' },
        { id: '0adfd74a-15df-11e7-f182-0a921c72c30a',
            source_id: '',
            variant_source_id: '',
            handle: 'SilverPendantNecklace',
            type: 'Fashion',
            has_variants: true,
            variant_parent_id: '',
            variant_option_one_name: 'Gemstone Color',
            variant_option_one_value: 'Aquamarine',
            variant_option_two_name: '',
            variant_option_two_value: '',
            variant_option_three_name: '',
            variant_option_three_value: '',
            active: true,
            name: 'Silver Pendant Necklace / Aquamarine',
            base_name: 'Silver Pendant Necklace',
            description: 'Silver necklace with small stone pendant',
            image: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-thumb.png',
            image_large: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-original.png',
            images: [],
            sku: '10013',
            tags: 'Necklace',
            brand_id: '0adfd74a-15df-11e7-f182-0a921c7a5746',
            brand_name: 'Forever Diamonds',
            supplier_name: 'FD Ltd',
            supplier_code: '',
            supply_price: '15.00',
            account_code_purchase: '',
            account_code_sales: '',
            track_inventory: true,
            button_order: '',
            inventory: [Object],
            price_book_entries: [Object],
            price: 60.86957,
            tax: 9.13044,
            tax_id: '0adfd74a-1555-11e7-f182-0a921c213ccb',
            tax_rate: 0.15,
            tax_name: 'GST',
            taxes: [Object],
            display_retail_price_tax_inclusive: 1,
            updated_at: '2017-03-16 21:47:12',
            deleted_at: '' },
        { id: '0adfd74a-15df-11e7-f182-0a921c837424',
            source_id: '',
            variant_source_id: '',
            handle: 'SilverPendantNecklace',
            type: 'Fashion',
            has_variants: false,
            variant_parent_id: '0adfd74a-15df-11e7-f182-0a921c72c30a',
            variant_option_one_name: 'Gemstone Color',
            variant_option_one_value: 'Smoky Quartz',
            variant_option_two_name: '',
            variant_option_two_value: '',
            variant_option_three_name: '',
            variant_option_three_value: '',
            active: true,
            name: 'Silver Pendant Necklace / Smoky Quartz',
            base_name: 'Silver Pendant Necklace',
            description: 'Silver necklace with small stone pendant',
            image: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-thumb.png',
            image_large: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-original.png',
            images: [],
            sku: '10014',
            tags: '',
            brand_id: '0adfd74a-15df-11e7-f182-0a921c7a5746',
            brand_name: 'Forever Diamonds',
            supplier_name: 'FD Ltd',
            supplier_code: '',
            supply_price: '10.00',
            account_code_purchase: '',
            account_code_sales: '',
            track_inventory: true,
            button_order: '',
            inventory: [Object],
            price_book_entries: [Object],
            price: 43.47826,
            tax: 6.52174,
            tax_id: '0adfd74a-1555-11e7-f182-0a921c213ccb',
            tax_rate: 0.15,
            tax_name: 'GST',
            taxes: [Object],
            display_retail_price_tax_inclusive: 1,
            updated_at: '2017-03-16 21:47:12',
            deleted_at: '' },
        { id: '0adfd74a-15df-11e7-f182-0a921c92d85d',
            source_id: '',
            variant_source_id: '',
            handle: 'SummerDress',
            type: 'Fashion',
            has_variants: true,
            variant_parent_id: '',
            variant_option_one_name: 'Size',
            variant_option_one_value: '6',
            variant_option_two_name: '',
            variant_option_two_value: '',
            variant_option_three_name: '',
            variant_option_three_value: '',
            active: true,
            name: 'Summer Dress / 6',
            base_name: 'Summer Dress',
            description: 'A light summer floral dress.',
            image: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-thumb.png',
            image_large: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-original.png',
            images: [],
            sku: '10015',
            tags: 'Summer, Womens, Cotton',
            brand_id: '0adfd74a-15df-11e7-f182-0a921c9aa8a3',
            brand_name: 'Summerly',
            supplier_name: 'Nomad Fashions',
            supplier_code: '',
            supply_price: '30.00',
            account_code_purchase: '',
            account_code_sales: '',
            track_inventory: true,
            button_order: '',
            inventory: [Object],
            price_book_entries: [Object],
            price: 108.69565,
            tax: 16.30435,
            tax_id: '0adfd74a-1555-11e7-f182-0a921c213ccb',
            tax_rate: 0.15,
            tax_name: 'GST',
            taxes: [Object],
            display_retail_price_tax_inclusive: 1,
            updated_at: '2017-03-16 21:47:12',
            deleted_at: '' },
        { id: '0adfd74a-15df-11e7-f182-0a921ca56d02',
            source_id: '',
            variant_source_id: '',
            handle: 'SummerDress',
            type: 'Fashion',
            has_variants: false,
            variant_parent_id: '0adfd74a-15df-11e7-f182-0a921c92d85d',
            variant_option_one_name: 'Size',
            variant_option_one_value: '8',
            variant_option_two_name: '',
            variant_option_two_value: '',
            variant_option_three_name: '',
            variant_option_three_value: '',
            active: true,
            name: 'Summer Dress / 8',
            base_name: 'Summer Dress',
            description: 'A light summer floral dress.',
            image: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-thumb.png',
            image_large: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-original.png',
            images: [],
            sku: '10016',
            tags: '',
            brand_id: '0adfd74a-15df-11e7-f182-0a921c9aa8a3',
            brand_name: 'Summerly',
            supplier_name: 'Nomad Fashions',
            supplier_code: '',
            supply_price: '30.00',
            account_code_purchase: '',
            account_code_sales: '',
            track_inventory: true,
            button_order: '',
            inventory: [Object],
            price_book_entries: [Object],
            price: 108.69565,
            tax: 16.30435,
            tax_id: '0adfd74a-1555-11e7-f182-0a921c213ccb',
            tax_rate: 0.15,
            tax_name: 'GST',
            taxes: [Object],
            display_retail_price_tax_inclusive: 1,
            updated_at: '2017-03-16 21:47:12',
            deleted_at: '' },
        { id: '0adfd74a-15df-11e7-f182-0a921cb36966',
            source_id: '',
            variant_source_id: '',
            handle: 'SummerDress',
            type: 'Fashion',
            has_variants: false,
            variant_parent_id: '0adfd74a-15df-11e7-f182-0a921c92d85d',
            variant_option_one_name: 'Size',
            variant_option_one_value: '10',
            variant_option_two_name: '',
            variant_option_two_value: '',
            variant_option_three_name: '',
            variant_option_three_value: '',
            active: true,
            name: 'Summer Dress / 10',
            base_name: 'Summer Dress',
            description: 'A light summer floral dress.',
            image: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-thumb.png',
            image_large: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-original.png',
            images: [],
            sku: '10017',
            tags: '',
            brand_id: '0adfd74a-15df-11e7-f182-0a921c9aa8a3',
            brand_name: 'Summerly',
            supplier_name: 'Nomad Fashions',
            supplier_code: '',
            supply_price: '30.00',
            account_code_purchase: '',
            account_code_sales: '',
            track_inventory: true,
            button_order: '',
            inventory: [Object],
            price_book_entries: [Object],
            price: 108.69565,
            tax: 16.30435,
            tax_id: '0adfd74a-1555-11e7-f182-0a921c213ccb',
            tax_rate: 0.15,
            tax_name: 'GST',
            taxes: [Object],
            display_retail_price_tax_inclusive: 1,
            updated_at: '2017-03-16 21:47:12',
            deleted_at: '' },
        { id: '0adfd74a-15df-11e7-f182-0a921cc0f27a',
            source_id: '',
            variant_source_id: '',
            handle: 'SummerDress',
            type: 'Fashion',
            has_variants: false,
            variant_parent_id: '0adfd74a-15df-11e7-f182-0a921c92d85d',
            variant_option_one_name: 'Size',
            variant_option_one_value: '12',
            variant_option_two_name: '',
            variant_option_two_value: '',
            variant_option_three_name: '',
            variant_option_three_value: '',
            active: true,
            name: 'Summer Dress / 12',
            base_name: 'Summer Dress',
            description: 'A light summer floral dress.',
            image: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-thumb.png',
            image_large: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-original.png',
            images: [],
            sku: '10018',
            tags: '',
            brand_id: '0adfd74a-15df-11e7-f182-0a921c9aa8a3',
            brand_name: 'Summerly',
            supplier_name: 'Nomad Fashions',
            supplier_code: '',
            supply_price: '30.00',
            account_code_purchase: '',
            account_code_sales: '',
            track_inventory: true,
            button_order: '',
            inventory: [Object],
            price_book_entries: [Object],
            price: 108.69565,
            tax: 16.30435,
            tax_id: '0adfd74a-1555-11e7-f182-0a921c213ccb',
            tax_rate: 0.15,
            tax_name: 'GST',
            taxes: [Object],
            display_retail_price_tax_inclusive: 1,
            updated_at: '2017-03-16 21:47:12',
            deleted_at: '' },
        { id: '0adfd74a-15df-11e7-f182-0a921d2ea089',
            source_id: '',
            variant_source_id: '',
            handle: 'vend-discount',
            type: '',
            has_variants: false,
            variant_parent_id: '',
            variant_option_one_name: '',
            variant_option_one_value: '',
            variant_option_two_name: '',
            variant_option_two_value: '',
            variant_option_three_name: '',
            variant_option_three_value: '',
            active: true,
            name: 'Discount',
            base_name: 'Discount',
            description: 'Discount product',
            image: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-thumb.png',
            image_large: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-original.png',
            images: [],
            sku: 'vend-discount',
            tags: '',
            brand_id: '',
            brand_name: '',
            supplier_name: '',
            supplier_code: '',
            supply_price: '0.00',
            account_code_purchase: '',
            account_code_sales: '',
            track_inventory: true,
            button_order: '',
            inventory: [],
            price_book_entries: [Object],
            price: 0,
            tax: 0,
            tax_id: '0adfd74a-1555-11e7-f182-0a921c213ccb',
            tax_rate: 0.15,
            tax_name: 'GST',
            taxes: [Object],
            display_retail_price_tax_inclusive: 1,
            updated_at: '2017-03-16 21:47:12',
            deleted_at: '' },
        { id: '0adfd74a-15df-11e7-f182-0a921cd091ae',
            source_id: '',
            variant_source_id: '',
            handle: 'DressShirt',
            type: 'Fashion',
            has_variants: true,
            variant_parent_id: '',
            variant_option_one_name: 'Fabric',
            variant_option_one_value: 'Cotton',
            variant_option_two_name: 'Size',
            variant_option_two_value: 'Small',
            variant_option_three_name: '',
            variant_option_three_value: '',
            active: false,
            name: 'Dress Shirt / Cotton / Small',
            base_name: 'Dress Shirt',
            description: 'Long sleeved pin stripped shirt.',
            image: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-thumb.png',
            image_large: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-original.png',
            images: [],
            sku: '10019',
            tags: 'Mens, Winter',
            brand_id: '0adfd74a-15df-11e7-f182-0a921cd7dd91',
            brand_name: 'Dress to Impress',
            supplier_name: 'Lewis Apparel',
            supplier_code: '',
            supply_price: '20.00',
            account_code_purchase: '',
            account_code_sales: '',
            track_inventory: true,
            button_order: '',
            inventory: [Object],
            price_book_entries: [Object],
            price: 78.26087,
            tax: 11.73913,
            tax_id: '0adfd74a-1555-11e7-f182-0a921c213ccb',
            tax_rate: 0.15,
            tax_name: 'GST',
            taxes: [Object],
            display_retail_price_tax_inclusive: 1,
            updated_at: '2017-03-23 04:56:45',
            deleted_at: '' },
        { id: '0adfd74a-15df-11e7-f182-0a921ce340ab',
            source_id: '',
            variant_source_id: '',
            handle: 'DressShirt',
            type: 'Fashion',
            has_variants: false,
            variant_parent_id: '0adfd74a-15df-11e7-f182-0a921cd091ae',
            variant_option_one_name: 'Fabric',
            variant_option_one_value: 'Cotton',
            variant_option_two_name: 'Size',
            variant_option_two_value: 'Medium',
            variant_option_three_name: '',
            variant_option_three_value: '',
            active: false,
            name: 'Dress Shirt / Cotton / Medium',
            base_name: 'Dress Shirt',
            description: 'Long sleeved pin stripped shirt.',
            image: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-thumb.png',
            image_large: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-original.png',
            images: [],
            sku: '10020',
            tags: '',
            brand_id: '0adfd74a-15df-11e7-f182-0a921cd7dd91',
            brand_name: 'Dress to Impress',
            supplier_name: 'Lewis Apparel',
            supplier_code: '',
            supply_price: '20.00',
            account_code_purchase: '',
            account_code_sales: '',
            track_inventory: true,
            button_order: '',
            inventory: [Object],
            price_book_entries: [Object],
            price: 78.26087,
            tax: 11.73913,
            tax_id: '0adfd74a-1555-11e7-f182-0a921c213ccb',
            tax_rate: 0.15,
            tax_name: 'GST',
            taxes: [Object],
            display_retail_price_tax_inclusive: 1,
            updated_at: '2017-03-23 04:56:45',
            deleted_at: '' },
        { id: '0adfd74a-15df-11e7-f182-0a921cf23b9c',
            source_id: '',
            variant_source_id: '',
            handle: 'DressShirt',
            type: 'Fashion',
            has_variants: false,
            variant_parent_id: '0adfd74a-15df-11e7-f182-0a921cd091ae',
            variant_option_one_name: 'Fabric',
            variant_option_one_value: 'Cotton',
            variant_option_two_name: 'Size',
            variant_option_two_value: 'Large',
            variant_option_three_name: '',
            variant_option_three_value: '',
            active: false,
            name: 'Dress Shirt / Cotton / Large',
            base_name: 'Dress Shirt',
            description: 'Long sleeved pin stripped shirt.',
            image: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-thumb.png',
            image_large: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-original.png',
            images: [],
            sku: '10021',
            tags: '',
            brand_id: '0adfd74a-15df-11e7-f182-0a921cd7dd91',
            brand_name: 'Dress to Impress',
            supplier_name: 'Lewis Apparel',
            supplier_code: '',
            supply_price: '20.00',
            account_code_purchase: '',
            account_code_sales: '',
            track_inventory: true,
            button_order: '',
            inventory: [Object],
            price_book_entries: [Object],
            price: 78.26087,
            tax: 11.73913,
            tax_id: '0adfd74a-1555-11e7-f182-0a921c213ccb',
            tax_rate: 0.15,
            tax_name: 'GST',
            taxes: [Object],
            display_retail_price_tax_inclusive: 1,
            updated_at: '2017-03-23 04:56:45',
            deleted_at: '' },
        { id: '0adfd74a-15df-11e7-f182-0a921d019d01',
            source_id: '',
            variant_source_id: '',
            handle: 'DressShirt',
            type: 'Fashion',
            has_variants: false,
            variant_parent_id: '0adfd74a-15df-11e7-f182-0a921cd091ae',
            variant_option_one_name: 'Fabric',
            variant_option_one_value: 'Polyester',
            variant_option_two_name: 'Size',
            variant_option_two_value: 'Small',
            variant_option_three_name: '',
            variant_option_three_value: '',
            active: false,
            name: 'Dress Shirt / Polyester / Small',
            base_name: 'Dress Shirt',
            description: 'Long sleeved pin stripped shirt.',
            image: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-thumb.png',
            image_large: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-original.png',
            images: [],
            sku: '10022',
            tags: '',
            brand_id: '0adfd74a-15df-11e7-f182-0a921cd7dd91',
            brand_name: 'Dress to Impress',
            supplier_name: 'Lewis Apparel',
            supplier_code: '',
            supply_price: '60.00',
            account_code_purchase: '',
            account_code_sales: '',
            track_inventory: true,
            button_order: '',
            inventory: [Object],
            price_book_entries: [Object],
            price: 65.21739,
            tax: 9.78261,
            tax_id: '0adfd74a-1555-11e7-f182-0a921c213ccb',
            tax_rate: 0.15,
            tax_name: 'GST',
            taxes: [Object],
            display_retail_price_tax_inclusive: 1,
            updated_at: '2017-03-23 04:56:45',
            deleted_at: '' },
        { id: '0adfd74a-15df-11e7-f182-0a921d10d9ac',
            source_id: '',
            variant_source_id: '',
            handle: 'DressShirt',
            type: 'Fashion',
            has_variants: false,
            variant_parent_id: '0adfd74a-15df-11e7-f182-0a921cd091ae',
            variant_option_one_name: 'Fabric',
            variant_option_one_value: 'Polyester',
            variant_option_two_name: 'Size',
            variant_option_two_value: 'Medium',
            variant_option_three_name: '',
            variant_option_three_value: '',
            active: false,
            name: 'Dress Shirt / Polyester / Medium',
            base_name: 'Dress Shirt',
            description: 'Long sleeved pin stripped shirt.',
            image: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-thumb.png',
            image_large: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-original.png',
            images: [],
            sku: '10023',
            tags: '',
            brand_id: '0adfd74a-15df-11e7-f182-0a921cd7dd91',
            brand_name: 'Dress to Impress',
            supplier_name: 'Lewis Apparel',
            supplier_code: '',
            supply_price: '60.00',
            account_code_purchase: '',
            account_code_sales: '',
            track_inventory: true,
            button_order: '',
            inventory: [Object],
            price_book_entries: [Object],
            price: 65.21739,
            tax: 9.78261,
            tax_id: '0adfd74a-1555-11e7-f182-0a921c213ccb',
            tax_rate: 0.15,
            tax_name: 'GST',
            taxes: [Object],
            display_retail_price_tax_inclusive: 1,
            updated_at: '2017-03-23 04:56:45',
            deleted_at: '' },
        { id: '0adfd74a-15df-11e7-f182-0a921d1fd7a8',
            source_id: '',
            variant_source_id: '',
            handle: 'DressShirt',
            type: 'Fashion',
            has_variants: false,
            variant_parent_id: '0adfd74a-15df-11e7-f182-0a921cd091ae',
            variant_option_one_name: 'Fabric',
            variant_option_one_value: 'Polyester',
            variant_option_two_name: 'Size',
            variant_option_two_value: 'Large',
            variant_option_three_name: '',
            variant_option_three_value: '',
            active: false,
            name: 'Dress Shirt / Polyester / Large',
            base_name: 'Dress Shirt',
            description: 'Long sleeved pin stripped shirt.',
            image: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-thumb.png',
            image_large: 'https://seekstock.vendhq.com/images/placeholder/product/no-image-white-original.png',
            images: [],
            sku: '10024',
            tags: '',
            brand_id: '0adfd74a-15df-11e7-f182-0a921cd7dd91',
            brand_name: 'Dress to Impress',
            supplier_name: 'Lewis Apparel',
            supplier_code: '',
            supply_price: '60.00',
            account_code_purchase: '',
            account_code_sales: '',
            track_inventory: true,
            button_order: '',
            inventory: [Object],
            price_book_entries: [Object],
            price: 65.21739,
            tax: 9.78261,
            tax_id: '0adfd74a-1555-11e7-f182-0a921c213ccb',
            tax_rate: 0.15,
            tax_name: 'GST',
            taxes: [Object],
            display_retail_price_tax_inclusive: 1,
            updated_at: '2017-03-23 04:56:45',
            deleted_at: '' } ] };

var results = [];
var handle = '';
var cell;
raw.products.forEach(item=>{
    if(!isNaN(item.sku)){
        if(handle!=item.handle){
            handle=item.handle;
            cell&&results.push(cell);
            cell = {
                "sku":  item.id,
                "category": item.type,
                "description":item.base_name,
                "variations":[],
                "active":item.active,
                "tags":item.tags,
                "longDescription":item.description,
            };
            var param={};
            param[item.variant_option_one_name]=item.variant_option_one_value;
            param[item.variant_option_two_name]=item.variant_option_two_value;
            param[item.variant_option_three_name]=item.variant_option_three_value;
            var variation = {
                "sku":item.sku,
                "image":item.image_large,
                "size":param.Size?param.Size:"N/A",
                "colour":param.Colour?param.Colour:"N/A",
                "fit":param.Fit?param.Fit:"N/A",
                "brand":item.brand_name,
                "rrp": '$'+item.supply_price
            }
            cell.variations.push(variation);
        }else{
            var param={};
            param[item.variant_option_one_name]=item.variant_option_one_value;
            param[item.variant_option_two_name]=item.variant_option_two_value;
            param[item.variant_option_three_name]=item.variant_option_three_value;
            var variation = {
                "sku":item.sku,
                "image":item.image_large,
                "size":param.Size?param.Size:"N/A",
                "colour":param.Colour?param.Colour:"N/A",
                "fit":param.Fit?param.Fit:"N/A",
                "brand":item.brand_name,
                "rrp": '$'+item.supply_price
            }
            cell.variations.push(variation);
        }
    };
});
results.push(cell);
console.log(JSON.stringify({results:results}));
